// @ts-nocheck
import type { PastCandidate, SourcingCampaign, EngagementEvent } from './types';

export const mockPastCandidates: PastCandidate[] = [
  {
    id: '1',
    name: 'Alex Rivera',
    currentTitle: 'Senior Full-Stack Developer',
    location: 'San Francisco, CA',
    experienceYears: 8,
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
    matchScore: 92,
    lastActive: '2025-02-15',
    matchReasons: ['React Expert', '8+ Years Exp', 'Previously Interviewed'],
    appliedBefore: 'Senior Frontend Engineer — Jan 2025',
    availability: 'open_to_work',
  },
  {
    id: '2',
    name: 'Priya Patel',
    currentTitle: 'Product Designer Lead',
    location: 'Remote',
    experienceYears: 6,
    skills: ['Figma', 'User Research', 'Design Systems', 'Prototyping', 'CSS'],
    matchScore: 87,
    lastActive: '2025-01-28',
    matchReasons: ['Design Systems', 'Remote Ready', 'High Interview Score'],
    appliedBefore: 'UX Designer — Nov 2024',
    availability: 'available',
  },
  {
    id: '3',
    name: 'Marcus Johnson',
    currentTitle: 'DevOps Engineer',
    location: 'Austin, TX',
    experienceYears: 5,
    skills: ['Kubernetes', 'Docker', 'CI/CD', 'Terraform', 'AWS'],
    matchScore: 84,
    lastActive: '2025-03-01',
    matchReasons: ['DevOps Skills', 'AWS Certified', 'Cultural Fit'],
    appliedBefore: 'Cloud Engineer — Dec 2024',
    availability: 'available',
  },
  {
    id: '4',
    name: 'Sophie Chen',
    currentTitle: 'Data Scientist',
    location: 'New York, NY',
    experienceYears: 4,
    skills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'Data Visualization'],
    matchScore: 79,
    lastActive: '2024-12-20',
    matchReasons: ['ML Experience', 'Python Skills', 'Strong Portfolio'],
    appliedBefore: 'ML Engineer — Sep 2024',
    availability: 'not_available',
  },
  {
    id: '5',
    name: 'Omar Al-Farsi',
    currentTitle: 'Backend Developer',
    location: 'Dubai, UAE',
    experienceYears: 7,
    skills: ['Java', 'Spring Boot', 'Microservices', 'Redis', 'MongoDB'],
    matchScore: 76,
    lastActive: '2025-02-05',
    matchReasons: ['Backend Expert', '7+ Years Exp', 'International'],
    appliedBefore: 'Senior Backend Dev — Oct 2024',
    availability: 'open_to_work',
  },
  {
    id: '6',
    name: 'Emma Williams',
    currentTitle: 'Engineering Manager',
    location: 'London, UK',
    experienceYears: 10,
    skills: ['Leadership', 'Agile', 'React', 'Node.js', 'Strategy'],
    matchScore: 73,
    lastActive: '2025-01-10',
    matchReasons: ['Leadership', 'Tech Background', 'Previously Offered'],
    appliedBefore: 'Tech Lead — Aug 2024',
    availability: 'available',
  },
];

export const mockCampaigns: SourcingCampaign[] = [
  {
    id: 'c1',
    name: 'Senior Frontend Engineer Search',
    jobId: 'j1',
    jobTitle: 'Senior Frontend Engineer',
    criteria: { skills: ['React', 'TypeScript', 'Next.js'], experience: 5, location: 'Remote' },
    matchedCount: 24,
    contactedCount: 18,
    respondedCount: 9,
    status: 'ACTIVE',
    createdAt: '2025-02-20',
  },
  {
    id: 'c2',
    name: 'Product Designer Pipeline',
    jobId: 'j2',
    jobTitle: 'Product Designer',
    criteria: { skills: ['Figma', 'User Research', 'Design Systems'], experience: 3, location: 'San Francisco' },
    matchedCount: 15,
    contactedCount: 12,
    respondedCount: 6,
    status: 'ACTIVE',
    createdAt: '2025-02-15',
  },
  {
    id: 'c3',
    name: 'DevOps Talent Pool',
    jobId: null,
    jobTitle: null,
    criteria: { skills: ['Kubernetes', 'Docker', 'CI/CD', 'AWS'], experience: 4 },
    matchedCount: 32,
    contactedCount: 20,
    respondedCount: 11,
    status: 'PAUSED',
    createdAt: '2025-01-10',
  },
  {
    id: 'c4',
    name: 'Data Science Interns 2025',
    jobId: 'j3',
    jobTitle: 'Data Science Intern',
    criteria: { skills: ['Python', 'Machine Learning', 'SQL'], experience: 0, location: 'New York' },
    matchedCount: 45,
    contactedCount: 30,
    respondedCount: 22,
    status: 'COMPLETED',
    createdAt: '2024-11-01',
  },
];

export const mockEngagementEvents: EngagementEvent[] = [
  { id: 'e1', candidateId: '1', candidateName: 'Alex Rivera', type: 'EMAIL_SENT', campaignName: 'Senior Frontend Engineer Search', details: 'Initial outreach email sent', date: '2025-03-03T10:30:00Z' },
  { id: 'e2', candidateId: '2', candidateName: 'Priya Patel', type: 'EMAIL_OPENED', campaignName: 'Product Designer Pipeline', details: 'Email opened on mobile', date: '2025-03-03T09:15:00Z' },
  { id: 'e3', candidateId: '3', candidateName: 'Marcus Johnson', type: 'EMAIL_CLICKED', campaignName: 'DevOps Talent Pool', details: 'Clicked job link in email', date: '2025-03-02T16:45:00Z' },
  { id: 'e4', candidateId: '4', candidateName: 'Sophie Chen', type: 'INTERVIEW_SCHEDULED', campaignName: 'Data Science Interns 2025', details: 'Phone screen scheduled for March 10', date: '2025-03-02T14:20:00Z' },
  { id: 'e5', candidateId: '5', candidateName: 'Omar Al-Farsi', type: 'APPLIED', campaignName: 'Senior Frontend Engineer Search', details: 'Applied through campaign link', date: '2025-03-02T11:00:00Z' },
  { id: 'e6', candidateId: '6', candidateName: 'Emma Williams', type: 'VIEWED_PROFILE', campaignName: null, details: 'Viewed company career page', date: '2025-03-01T15:30:00Z' },
  { id: 'e7', candidateId: '1', candidateName: 'Alex Rivera', type: 'EMAIL_OPENED', campaignName: 'Senior Frontend Engineer Search', details: 'Email opened 2nd time', date: '2025-03-01T10:00:00Z' },
  { id: 'e8', candidateId: '2', candidateName: 'Priya Patel', type: 'INTERVIEW_SCHEDULED', campaignName: 'Product Designer Pipeline', details: 'Design challenge sent', date: '2025-02-28T13:45:00Z' },
  { id: 'e9', candidateId: '3', candidateName: 'Marcus Johnson', type: 'EMAIL_SENT', campaignName: 'DevOps Talent Pool', details: 'Follow-up email sent', date: '2025-02-27T09:30:00Z' },
  { id: 'e10', candidateId: '4', candidateName: 'Sophie Chen', type: 'APPLIED', campaignName: 'Data Science Interns 2025', details: 'Submitted application via re-engagement', date: '2025-02-26T17:00:00Z' },
];

export const mockJobs = [
  { id: 'j1', title: 'Senior Frontend Engineer' },
  { id: 'j2', title: 'Product Designer' },
  { id: 'j3', title: 'Data Science Intern' },
  { id: 'j4', title: 'Backend Developer' },
  { id: 'j5', title: 'DevOps Engineer' },
];
