import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { logAuthEvent } from '@/lib/security/auth-logger';
import { createSafeErrorResponse } from '@/lib/security/error-handler';
import { getClientIp } from '@/lib/security';

export async function GET(request: NextRequest) {
  const clientIp = getClientIp(request.headers);
  const { searchParams } = new URL(request.url);
  const token = searchParams.get('token');

  if (!token) {
    return NextResponse.json(
      { error: 'Verification token is required' },
      { status: 400 }
    );
  }

  try {
    // For email verification, tokens are stored as plain text (not hashed)
    // because they are generated by the register route without hashing
    // Look up the token directly
    let verificationToken = await db.verificationToken.findFirst({
      where: { token: token },
    });

    // If not found with plain token, try hashing it (for backward compat with password reset tokens)
    if (!verificationToken) {
      const crypto = await import('crypto');
      const hashedToken = crypto.createHash('sha256').update(token).digest('hex');
      verificationToken = await db.verificationToken.findUnique({
        where: { token: hashedToken },
      });
    }

    if (!verificationToken) {
      return NextResponse.json(
        { error: 'Invalid verification link', code: 'INVALID' },
        { status: 400 }
      );
    }

    // Check if token is not expired
    if (verificationToken.expires < new Date()) {
      // Delete expired token
      try {
        await db.verificationToken.delete({
          where: {
            identifier_token: {
              identifier: verificationToken.identifier,
              token: verificationToken.token,
            },
          },
        });
      } catch {
        // Token may have already been deleted
      }

      return NextResponse.json(
        { error: 'Verification link has expired', code: 'EXPIRED' },
        { status: 400 }
      );
    }

    // Find user by identifier (email)
    const user = await db.user.findUnique({
      where: { email: verificationToken.identifier },
    });

    if (!user) {
      return NextResponse.json(
        { error: 'User not found' },
        { status: 400 }
      );
    }

    // Update user: emailVerified = new Date()
    await db.user.update({
      where: { id: user.id },
      data: { emailVerified: new Date() },
    });

    // Delete the used token
    try {
      await db.verificationToken.delete({
        where: {
          identifier_token: {
            identifier: verificationToken.identifier,
            token: verificationToken.token,
          },
        },
      });
    } catch {
      // Token may have already been deleted
    }

    // Log the event
    await logAuthEvent({
      eventType: 'LOGIN_SUCCESS',
      userId: user.id,
      email: user.email,
      ipAddress: clientIp,
      details: 'Email verified successfully',
    });

    return NextResponse.json({
      message: 'Email verified successfully',
      verified: true,
    });
  } catch (error) {
    return createSafeErrorResponse(error, {
      status: 500,
      publicMessage: 'An error occurred during email verification',
      logContext: 'VerifyEmail',
    });
  }
}
